language: bash
services: docker

env:
    - SUITE=stable   CODENAME=jessie  TIMESTAMP=2017-01-01T00:00:00Z SHA256=c3f1697c699487382d5d15e4462c0e84b3069d3fc29ca100914c20258aa8ecc3
    - SUITE=jessie   CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=c3f1697c699487382d5d15e4462c0e84b3069d3fc29ca100914c20258aa8ecc3
    - SUITE=testing  CODENAME=stretch TIMESTAMP=2017-01-01T00:00:00Z SHA256=e9679f1070950a6bdd9b56206e43dc32a9a89bb1e850cdc0e213b69e72f137b5
    - SUITE=stretch  CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=e9679f1070950a6bdd9b56206e43dc32a9a89bb1e850cdc0e213b69e72f137b5
    - SUITE=unstable CODENAME=sid     TIMESTAMP=2017-01-01T00:00:00Z SHA256=e78b061b4cbcafc5fc6011b83eaa996851207f80b178ec7ae763f6dcda5e775f
    - SUITE=sid      CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=e78b061b4cbcafc5fc6011b83eaa996851207f80b178ec7ae763f6dcda5e775f
    - SUITE=oldstable CODENAME=wheezy TIMESTAMP=2017-01-01T00:00:00Z SHA256=59387392aa63da1f77ea28be581a4b2d8e7e9720121d1d563a3f0cb4356f9856
    - SUITE=wheezy    CODENAME=       TIMESTAMP=2017-01-01T00:00:00Z SHA256=59387392aa63da1f77ea28be581a4b2d8e7e9720121d1d563a3f0cb4356f9856
    # EOL suites testing
    - SUITE=eol CODENAME=etch            TIMESTAMP=2017-01-01T00:00:00Z SHA256=11257bba9c16e146184e9715a3ec89db4f701bb71d1a4f416e29a68fb20928ff
    - SUITE=eol CODENAME=woody ARCH=i386 TIMESTAMP=2017-01-01T00:00:00Z SHA256=79645a893e1e39a5421a15ba54e20724704b407d9fbb5bbef146a8b03863d1cf
    # qemu-debootstrap testing
    - ARCH=arm64 SUITE=jessie CODENAME= TIMESTAMP=2017-01-01T00:00:00Z SHA256=a54b0b74f32d2c03f4036e7c305672471553ac18682ba109d9481da31069dc94
    # a few entries for "today" to try and catch issues like https://github.com/debuerreotype/debuerreotype/issues/41 sooner
    - SUITE=unstable  CODENAME= TIMESTAMP="today 00:00:00" SHA256=
    - SUITE=stable    CODENAME= TIMESTAMP="today 00:00:00" SHA256=
    - SUITE=oldstable CODENAME= TIMESTAMP="today 00:00:00" SHA256=

addons:
    apt:
        packages:
            - binfmt-support
            - qemu-user-static

before_script:
    - docker run -d --name squignix --restart always tianon/squignix # TODO temporary!! (once https://github.com/tianon/pgp-happy-eyeballs/tree/travis-squignix is deleted, this should be) -- squignix is necessary for building etch and woody who otherwise are so poorly behaved they get rate limited by snapshot.d.o (https://travis-ci.org/debuerreotype/debuerreotype/builds/479633791)
    - wget -qO- https://github.com/tianon/pgp-happy-eyeballs/raw/713f2a81bf3eac1752f0c41b271444f5b57e93c9/hack-my-builds.sh | bash

script:
    - travis_retry ./.travis.sh

after_script:
    - docker images
    - docker logs rawdns
    - docker logs squignix # TODO temporary!! (see above)
