language: bash
services: docker

env:
    - SUITE=jessie   CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=29ac0469fb58500a9e02044dbba11f8f583a3fb73e9dafed8cd18bb816e756ed
    - SUITE=stable   CODENAME=jessie  TIMESTAMP=2017-01-01T00:00:00Z SHA256=29ac0469fb58500a9e02044dbba11f8f583a3fb73e9dafed8cd18bb816e756ed
    - SUITE=stretch  CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=b60e23c7592f9a1037bf27807911a6f0b0b1952ab51913afcd732a3e4784d575
    - SUITE=testing  CODENAME=stretch TIMESTAMP=2017-01-01T00:00:00Z SHA256=b60e23c7592f9a1037bf27807911a6f0b0b1952ab51913afcd732a3e4784d575
    - SUITE=sid      CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=b1b26e921f13306bc86d3d059fa5fd898ed4c84b15ca5de100d7baf9f282bbc0
    - SUITE=unstable CODENAME=sid     TIMESTAMP=2017-01-01T00:00:00Z SHA256=b1b26e921f13306bc86d3d059fa5fd898ed4c84b15ca5de100d7baf9f282bbc0
    - SUITE=wheezy    CODENAME=       TIMESTAMP=2017-01-01T00:00:00Z SHA256=94aac7c0dde96024d3c09d8ed1711b392b415e70f89d36407d27bebd7e8f0a21
    - SUITE=oldstable CODENAME=wheezy TIMESTAMP=2017-01-01T00:00:00Z SHA256=94aac7c0dde96024d3c09d8ed1711b392b415e70f89d36407d27bebd7e8f0a21
    # EOL suites testing
    - SUITE=eol CODENAME=etch            TIMESTAMP=2016-03-13T13:03:28Z SHA256=82f368d4dd0257603e9091fa3e2511d90cff16188f95414e7b3bff260b927d2d
    - SUITE=eol CODENAME=woody ARCH=i386 TIMESTAMP=2016-03-13T13:03:28Z SHA256=e7db9c0074b2fff8feca7cd273a89ee37275731c409c8c496043f5a1c7ff8d83
    # qemu-debootstrap testing
    - ARCH=arm64 SUITE=jessie CODENAME= TIMESTAMP=2017-01-01T00:00:00Z SHA256=f6f2ba94b0554e5f2485abcb1b36a5b976d7c9c07c7c2af2301c7652274bd797

addons:
    apt:
        packages:
            - binfmt-support
            - qemu-user-static

script:
    - travis_retry ./.travis.sh

after_script:
    - docker images
