language: bash
services: docker

env:
    - SUITE=jessie   CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=a45cc1c48e4b44344307dfbd60001de1bfd9595dac0d8673913bf6157a9c5753
    - SUITE=stable   CODENAME=jessie  TIMESTAMP=2017-01-01T00:00:00Z SHA256=a45cc1c48e4b44344307dfbd60001de1bfd9595dac0d8673913bf6157a9c5753
    - SUITE=stretch  CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=c7c10011dcaa13c52c35f0f142b3c9d2e24a15094fbe1edee0a9ca465f1f44c9
    - SUITE=testing  CODENAME=stretch TIMESTAMP=2017-01-01T00:00:00Z SHA256=c7c10011dcaa13c52c35f0f142b3c9d2e24a15094fbe1edee0a9ca465f1f44c9
    - SUITE=sid      CODENAME=        TIMESTAMP=2017-01-01T00:00:00Z SHA256=b75b4496deb4d6cee32245e4125e7ef948b09afbeb1ef3b9669e56daf3e822a7
    - SUITE=unstable CODENAME=sid     TIMESTAMP=2017-01-01T00:00:00Z SHA256=b75b4496deb4d6cee32245e4125e7ef948b09afbeb1ef3b9669e56daf3e822a7
    - SUITE=wheezy    CODENAME=       TIMESTAMP=2017-01-01T00:00:00Z SHA256=33fd0e2a98130504db1f45694b1ce98e4a718ebfc3e3ace5d54050da1efb2a50
    - SUITE=oldstable CODENAME=wheezy TIMESTAMP=2017-01-01T00:00:00Z SHA256=33fd0e2a98130504db1f45694b1ce98e4a718ebfc3e3ace5d54050da1efb2a50
    - SUITE=eol CODENAME=etch TIMESTAMP=2016-03-13T13:03:28Z SHA256=36cd5d948b13c76e2ae2cef28d4b3b131d93ef244b5298af509ae2a7a839f84e

script:
    - travis_retry ./.travis.sh

after_script:
    - docker images
